// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HdD4IusPldrBQN6Po0CcpAZDMQBVFK0',
    appId: '1:170925070592:android:c34199d275dde2d2017be5',
    messagingSenderId: '170925070592',
    projectId: 'instagram-clone-course-sailesh',
    storageBucket: 'instagram-clone-course-sailesh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyV2Mju_A2onYfgiSJKGMwQtlwv0zRnoc',
    appId: '1:170925070592:ios:5fb11c854a15a967017be5',
    messagingSenderId: '170925070592',
    projectId: 'instagram-clone-course-sailesh',
    storageBucket: 'instagram-clone-course-sailesh.appspot.com',
    androidClientId:
        '170925070592-kaoao13fmd72544oqh5lpdo658rn394d.apps.googleusercontent.com',
    iosClientId:
        '170925070592-dishbghhbcpcs74p37ljqau84gbemrjl.apps.googleusercontent.com',
    iosBundleId: 'np.com.saileshdahal.authTest',
  );
}
